// <auto-generated />
using System;
using IotBbq.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IotBbq.Model.Migrations
{
    [DbContext(typeof(IotBbqContext))]
    [Migration("20181023021517_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("IotBbq.Model.BbqEvent", b =>
                {
                    b.Property<int>("BbqEventId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EventDate");

                    b.Property<string>("EventName");

                    b.HasKey("BbqEventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("IotBbq.Model.BbqModelItem", b =>
                {
                    b.Property<int>("BbqModelItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BbqEventId");

                    b.HasKey("BbqModelItemId");

                    b.HasIndex("BbqEventId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("IotBbq.Model.BbqModelItem", b =>
                {
                    b.HasOne("IotBbq.Model.BbqEvent")
                        .WithMany("Items")
                        .HasForeignKey("BbqEventId");
                });
#pragma warning restore 612, 618
        }
    }
}
